# Generated by Django 5.1.1 on 2024-12-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_salesorder_user"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="products",
            field=models.ManyToManyField(to="products.product"),
        ),
    ]
